server:
  port: 8888

spring:
  application:
    name: MiaoSha
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.9.189.141:3306/MiaoSha?serverTimezone=Asia/Shanghai
    username: root
    password: 114477
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.business
  mapper-locations:
    - mapper/*