package com.business.dao;

import com.business.dataObject.itemStockDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.RequestParam;

@Repository
public interface itemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Aug 21 16:37:52 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Aug 21 16:37:52 GMT+08:00 2021
     */
    int insert(itemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Aug 21 16:37:52 GMT+08:00 2021
     */
    int insertSelective(itemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Aug 21 16:37:52 GMT+08:00 2021
     */
    itemStockDO selectByPrimaryKey(Integer id);
    itemStockDO selectByItemId(Integer ItemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Aug 21 16:37:52 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(itemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Aug 21 16:37:52 GMT+08:00 2021
     */
    int updateByPrimaryKey(itemStockDO record);

    int decreaseStock(@Param("itemId") Integer itemId,@Param("amount") Integer amount);
}