package com.business.dao;

import com.business.dataObject.orderDO;

public interface orderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Aug 23 11:57:20 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Aug 23 11:57:20 GMT+08:00 2021
     */
    int insert(orderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Aug 23 11:57:20 GMT+08:00 2021
     */
    int insertSelective(orderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Aug 23 11:57:20 GMT+08:00 2021
     */
    orderDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Aug 23 11:57:20 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(orderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Aug 23 11:57:20 GMT+08:00 2021
     */
    int updateByPrimaryKey(orderDO record);
}