package com.business.dao;

import com.business.dataObject.sequenceDO;

public interface sequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Aug 23 13:20:17 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Aug 23 13:20:17 GMT+08:00 2021
     */
    int insert(sequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Aug 23 13:20:17 GMT+08:00 2021
     */
    int insertSelective(sequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Aug 23 13:20:17 GMT+08:00 2021
     */
    sequenceDO selectByPrimaryKey(String name);
    sequenceDO getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Aug 23 13:20:17 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(sequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Aug 23 13:20:17 GMT+08:00 2021
     */
    int updateByPrimaryKey(sequenceDO record);
}